spring:
  application:
    name: notification-service

  # Kafka properties
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://127.0.0.1:8085}

  # Mailtrap config
  mail:
    host: ${MAILTRAP_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAILTRAP_PORT:2525}
    username: ${MAILTRAP_USERNAME:320507215fd1af}
    password: ${MAILTRAP_PASSWORD:fe0f5ce461f8b0}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

  # Thymeleaf config
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 3006

# log config
logging:
  level:
    com.cinequest.notificationservice: DEBUG
    org.springframework.kafka: INFO
    org.springframework.mail: DEBUG

notification:
  from-email: noreply@cinequest.com
  from-name: CineQuest Team
