apiVersion: v1
kind: ConfigMap
metadata:
  name: cinequest-config
  namespace: cinequest
data:
  # Database URLs
  RATING_MONGODB_URI: "mongodb://root:password@rating-mongodb:27017/rating-service?authSource=admin"
  ACHIEVEMENT_MONGODB_URI: "mongodb://root:password@achievement-mongodb:27017/achievement-service?authSource=admin"
  SIGN_POSTGRES_URI: "jdbc:postgresql://sign-postgres:5432/sign"
  SIGN_POSTGRES_USER: "postgres"

  # Redis
  MOVIE_REDIS_HOST: "movie-redis"

  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  # Gateway URLs
  KEYCLOAK_SERVICE_URL: "http://keycloak:8080"
  MOVIE_SERVICE_URL: "http://movie-service:3002"
  RATING_SERVICE_URL: "http://rating-service:3003"
  SIGN_SERVICE_URL: "http://sign-service:3004"
  ACHIEVEMENT_SERVICE_URL: "http://achievement-service:3005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3006"

  # Keycloak
  KC_DB: "mysql"
  KC_DB_URL_HOST: "keycloak-mysql"
  KC_DB_URL_DATABASE: "keycloak"
  KC_DB_USERNAME: "keycloak"
  KC_HTTP_RELATIVE_PATH: "/keycloak"
  KC_PROXY: "edge"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"

  # Mailtrap
  MAILTRAP_HOST: "sandbox.smtp.mailtrap.io"
  MAILTRAP_PORT: "2525"
