apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: cinequest
type: Opaque
data:
  # echo -n "value" | base64
  postgres-user: cG9zdGdyZXM=       # postgres
  postgres-password: cGFzc3dvcmQ=   # password
  mongodb-username: cm9vdA==        # root
  mongodb-password: cGFzc3dvcmQ=    # password
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: cinequest
type: Opaque
data:
  mysql-root-password: cm9vdA==     # root
  mysql-user: a2V5Y2xvYWs=          # keycloak
  mysql-password: cGFzc3dvcmQ=      # password
  admin-user: YWRtaW4=              # admin
  admin-password: YWRtaW4=          # admin
---
apiVersion: v1
kind: Secret
metadata:
  name: mailtrap-secrets
  namespace: cinequest
type: Opaque
data:
  # My mailtrap credentials encoded in base64, free plan, no guarantee for future maintenance!
  mailtrap-username: MzIwNTA3MjE1ZmQxYWY=
  mailtrap-password: ZmUwZjVjZTQ2MWY4YjA=
---
apiVersion: v1
kind: Secret
metadata:
  name: tmdb-secrets
  namespace: cinequest
type: Opaque
data:
  # My TMDB API key encoded in base64, free plan, no guarantee for future maintenance!
  tmdb-api-key: ZjFhYjY2MmM5M2VlYjdkZDE2MWUyMjMzZmU1MjUwMWE=
