apiVersion: v1
kind: Secret
metadata:
  name: cinequest-secrets
  namespace: cinequest
type: Opaque
stringData:
  # TMDB API Key
  TMDB_API_KEY: "99251c0d1d286b8f592df2cac7ea065f"

  # Database Passwords
  POSTGRES_PASSWORD: "password"
  SIGN_POSTGRES_PASSWORD: "password"
  MONGO_ROOT_PASSWORD: "password"
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_PASSWORD: "password"
  KC_DB_PASSWORD: "password"

  # Keycloak
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"

  # Mailtrap
  MAILTRAP_USERNAME: "cadcd6f417175d"
  MAILTRAP_PASSWORD: "d67d43fd5f818f"
